name: flutter_jira_timetac
description: Desktop Flutter-App (Windows) zum Buchen von Timetac & Outlook (ICS) nach Jira Worklogs
publish_to: "none"
version: 4.0.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  file_picker: ^8.0.6
  provider: ^6.1.2
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  http: ^1.2.2
  collection: ^1.18.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
