name: chronos
description: Chronos - Time Tracking Efficiency
publish_to: "none"
version: 6.3.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  file_picker: ^8.0.6
  provider: ^6.1.2
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  http: ^1.2.2
  collection: ^1.18.0
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0
  archive: ^3.6.1
  flutter_markdown: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: false
  ios: false
  image_path: "assets/logo.png"
  windows:
    generate: true
    icon_size: 48
  macos:
    generate: true
  linux:
    generate: true
